@echo off
chcp 65001 > nul
echo 正在修复qentl.bat中文编码...

rem 创建临时目录
set TEMP_DIR=%~dp0..\temp_encoding
if not exist "%TEMP_DIR%" mkdir "%TEMP_DIR%"

rem 创建UTF-8版本的qentl.bat
echo @echo off > "%TEMP_DIR%\qentl.bat"
echo chcp 65001 ^>nul >> "%TEMP_DIR%\qentl.bat"
echo setlocal enabledelayedexpansion >> "%TEMP_DIR%\qentl.bat"
echo. >> "%TEMP_DIR%\qentl.bat"
echo REM QEntL启动器 - 简化版本 >> "%TEMP_DIR%\qentl.bat"
echo REM 提供测试运行、文件执行等功能 >> "%TEMP_DIR%\qentl.bat"
echo. >> "%TEMP_DIR%\qentl.bat"
echo set VERSION=0.1.0 >> "%TEMP_DIR%\qentl.bat"
echo set QENT_FILE=%%~dp0qentl.qent >> "%TEMP_DIR%\qentl.bat"
echo set TEST_DIR=%%~dp0..\tests >> "%TEMP_DIR%\qentl.bat"
echo set LOG_DIR=%%~dp0..\logs >> "%TEMP_DIR%\qentl.bat"
echo. >> "%TEMP_DIR%\qentl.bat"
echo echo QEntL环境初始化完成 - 已设置UTF-8编码支持 >> "%TEMP_DIR%\qentl.bat"
echo. >> "%TEMP_DIR%\qentl.bat"
echo REM 检查是否是测试命令 >> "%TEMP_DIR%\qentl.bat"
echo if "%%~1"=="test" ( >> "%TEMP_DIR%\qentl.bat"
echo     echo 启动测试... >> "%TEMP_DIR%\qentl.bat"
echo. >> "%TEMP_DIR%\qentl.bat"
echo     if "%%~2"=="" ( >> "%TEMP_DIR%\qentl.bat"
echo         echo 运行所有测试: >> "%TEMP_DIR%\qentl.bat"
echo. >> "%TEMP_DIR%\qentl.bat"
echo         for %%%%t in ^(quantum_state quantum_entanglement quantum_gene quantum_field^) do ^( >> "%TEMP_DIR%\qentl.bat"
echo             echo 运行测试: %%%%t >> "%TEMP_DIR%\qentl.bat"
echo             if exist "%%TEST_DIR%%\test_%%%%t.exe" ^( >> "%TEMP_DIR%\qentl.bat"
echo                 echo 执行: %%TEST_DIR%%\test_%%%%t.exe >> "%TEMP_DIR%\qentl.bat"
echo                 pushd "%%TEST_DIR%%" ^&^& test_%%%%t.exe >> "%TEMP_DIR%\qentl.bat"
echo                 popd >> "%TEMP_DIR%\qentl.bat"
echo             ^) else ^( >> "%TEMP_DIR%\qentl.bat"
echo                 echo 警告: 测试文件不存在 - %%TEST_DIR%%\test_%%%%t.exe >> "%TEMP_DIR%\qentl.bat"
echo             ^) >> "%TEMP_DIR%\qentl.bat"
echo             echo. >> "%TEMP_DIR%\qentl.bat"
echo         ^) >> "%TEMP_DIR%\qentl.bat"
echo. >> "%TEMP_DIR%\qentl.bat"
echo         echo 所有测试完成! >> "%TEMP_DIR%\qentl.bat"
echo     ^) else ^( >> "%TEMP_DIR%\qentl.bat"
echo         set TEST_NAME=%%~2 >> "%TEMP_DIR%\qentl.bat"
echo         if not "^!TEST_NAME:~0,5^!"=="test_" set TEST_NAME=test_^!TEST_NAME^! >> "%TEMP_DIR%\qentl.bat"
echo         if not "^!TEST_NAME:~-4^!"==".exe" ^( >> "%TEMP_DIR%\qentl.bat"
echo             if not "^!TEST_NAME:~-2^!"==".c" set TEST_NAME=^!TEST_NAME^!.c >> "%TEMP_DIR%\qentl.bat"
echo             set TEST_EXE=^!TEST_NAME:.c=.exe^! >> "%TEMP_DIR%\qentl.bat"
echo         ^) else ^( >> "%TEMP_DIR%\qentl.bat"
echo             set TEST_EXE=^!TEST_NAME^! >> "%TEMP_DIR%\qentl.bat"
echo         ^) >> "%TEMP_DIR%\qentl.bat"
echo. >> "%TEMP_DIR%\qentl.bat"
echo         echo 运行测试: ^!TEST_EXE^! >> "%TEMP_DIR%\qentl.bat"
echo         if exist "%%TEST_DIR%%\^!TEST_EXE^!" ^( >> "%TEMP_DIR%\qentl.bat"
echo             echo 执行: %%TEST_DIR%%\^!TEST_EXE^! >> "%TEMP_DIR%\qentl.bat"
echo             pushd "%%TEST_DIR%%" ^&^& ^!TEST_EXE^! >> "%TEMP_DIR%\qentl.bat"
echo             if ^!errorlevel^! EQU 0 ^( >> "%TEMP_DIR%\qentl.bat"
echo                 echo 测试通过! >> "%TEMP_DIR%\qentl.bat"
echo             ^) else ^( >> "%TEMP_DIR%\qentl.bat"
echo                 echo 测试失败! >> "%TEMP_DIR%\qentl.bat"
echo             ^) >> "%TEMP_DIR%\qentl.bat"
echo             popd >> "%TEMP_DIR%\qentl.bat"
echo         ^) else ^( >> "%TEMP_DIR%\qentl.bat"
echo             echo 错误: 测试文件不存在 - %%TEST_DIR%%\^!TEST_EXE^! >> "%TEMP_DIR%\qentl.bat"
echo         ^) >> "%TEMP_DIR%\qentl.bat"
echo     ^) >> "%TEMP_DIR%\qentl.bat"
echo. >> "%TEMP_DIR%\qentl.bat"
echo     exit /b %%errorlevel%% >> "%TEMP_DIR%\qentl.bat"
echo ^) >> "%TEMP_DIR%\qentl.bat"
echo. >> "%TEMP_DIR%\qentl.bat"
echo REM 处理其他命令 >> "%TEMP_DIR%\qentl.bat"
echo if "%%~1"=="--version" ^( >> "%TEMP_DIR%\qentl.bat"
echo     echo QEntl解释器 v%%VERSION%% >> "%TEMP_DIR%\qentl.bat"
echo     echo Quantum Entanglement Language Environment >> "%TEMP_DIR%\qentl.bat"
echo     exit /b 0 >> "%TEMP_DIR%\qentl.bat"
echo ^) >> "%TEMP_DIR%\qentl.bat"
echo. >> "%TEMP_DIR%\qentl.bat"
echo if "%%~1"=="--help" ^( >> "%TEMP_DIR%\qentl.bat"
echo     echo 用法: qentl [选项] [文件] >> "%TEMP_DIR%\qentl.bat"
echo     echo 选项: >> "%TEMP_DIR%\qentl.bat"
echo     echo   --version    显示版本信息 >> "%TEMP_DIR%\qentl.bat"
echo     echo   --help       显示帮助信息 >> "%TEMP_DIR%\qentl.bat"
echo     echo   test [文件]  运行测试文件，不指定文件则运行所有测试 >> "%TEMP_DIR%\qentl.bat"
echo     exit /b 0 >> "%TEMP_DIR%\qentl.bat"
echo ^) >> "%TEMP_DIR%\qentl.bat"
echo. >> "%TEMP_DIR%\qentl.bat"
echo REM 如果没有参数，显示帮助 >> "%TEMP_DIR%\qentl.bat"
echo if "%%~1"=="" ^( >> "%TEMP_DIR%\qentl.bat"
echo     echo 错误: 缺少文件名或选项 >> "%TEMP_DIR%\qentl.bat"
echo     echo 用法: qentl [选项] [文件] >> "%TEMP_DIR%\qentl.bat"
echo     echo 选项: >> "%TEMP_DIR%\qentl.bat"
echo     echo   --version    显示版本信息 >> "%TEMP_DIR%\qentl.bat"
echo     echo   --help       显示帮助信息 >> "%TEMP_DIR%\qentl.bat"
echo     echo   test [文件]  运行测试文件，不指定文件则运行所有测试 >> "%TEMP_DIR%\qentl.bat"
echo     exit /b 1 >> "%TEMP_DIR%\qentl.bat"
echo ^) >> "%TEMP_DIR%\qentl.bat"
echo. >> "%TEMP_DIR%\qentl.bat"
echo REM 假设是文件名 >> "%TEMP_DIR%\qentl.bat"
echo set FILENAME=%%~1 >> "%TEMP_DIR%\qentl.bat"
echo echo QEntl v%%VERSION%% - 执行文件: %%FILENAME%% >> "%TEMP_DIR%\qentl.bat"
echo. >> "%TEMP_DIR%\qentl.bat"
echo REM 检查文件是否存在 >> "%TEMP_DIR%\qentl.bat"
echo if not exist "%%FILENAME%%" ^( >> "%TEMP_DIR%\qentl.bat"
echo     echo 错误: 文件不存在 - %%FILENAME%% >> "%TEMP_DIR%\qentl.bat"
echo     exit /b 1 >> "%TEMP_DIR%\qentl.bat"
echo ^) >> "%TEMP_DIR%\qentl.bat"
echo. >> "%TEMP_DIR%\qentl.bat"
echo REM 检查文件扩展名是否支持 >> "%TEMP_DIR%\qentl.bat"
echo set FILE_EXT=%%~x1 >> "%TEMP_DIR%\qentl.bat"
echo set SUPPORTED=0 >> "%TEMP_DIR%\qentl.bat"
echo if /i "%%FILE_EXT%%"==".qpy" set SUPPORTED=1 >> "%TEMP_DIR%\qentl.bat"
echo if /i "%%FILE_EXT%%"==".qentl" set SUPPORTED=1 >> "%TEMP_DIR%\qentl.bat"
echo if /i "%%FILE_EXT%%"==".qent" set SUPPORTED=1 >> "%TEMP_DIR%\qentl.bat"
echo if /i "%%FILE_EXT%%"==".qjs" set SUPPORTED=1 >> "%TEMP_DIR%\qentl.bat"
echo if /i "%%FILE_EXT%%"==".qcss" set SUPPORTED=1 >> "%TEMP_DIR%\qentl.bat"
echo if /i "%%FILE_EXT%%"==".qml" set SUPPORTED=1 >> "%TEMP_DIR%\qentl.bat"
echo if /i "%%FILE_EXT%%"==".qsql" set SUPPORTED=1 >> "%TEMP_DIR%\qentl.bat"
echo if /i "%%FILE_EXT%%"==".qcon" set SUPPORTED=1 >> "%TEMP_DIR%\qentl.bat"
echo if /i "%%FILE_EXT%%"==".qtest" set SUPPORTED=1 >> "%TEMP_DIR%\qentl.bat"
echo if /i "%%FILE_EXT%%"==".qmod" set SUPPORTED=1 >> "%TEMP_DIR%\qentl.bat"
echo. >> "%TEMP_DIR%\qentl.bat"
echo if "%%SUPPORTED%%"=="0" ^( >> "%TEMP_DIR%\qentl.bat"
echo     echo 错误: 不支持的文件格式 - %%FILENAME%% >> "%TEMP_DIR%\qentl.bat"
echo     echo 支持的格式: .qpy, .qentl, .qent, .qjs, .qcss, .qml, .qsql, .qcon, .qtest, .qmod >> "%TEMP_DIR%\qentl.bat"
echo     exit /b 1 >> "%TEMP_DIR%\qentl.bat"
echo ^) >> "%TEMP_DIR%\qentl.bat"
echo. >> "%TEMP_DIR%\qentl.bat"
echo REM "执行"QEntL文件 >> "%TEMP_DIR%\qentl.bat"
echo echo 解析量子实体... >> "%TEMP_DIR%\qentl.bat"
echo echo 处理量子纠缠声明... >> "%TEMP_DIR%\qentl.bat"
echo echo 导入模块... >> "%TEMP_DIR%\qentl.bat"
echo echo 实例化对象... >> "%TEMP_DIR%\qentl.bat"
echo echo 执行量子代码... >> "%TEMP_DIR%\qentl.bat"
echo. >> "%TEMP_DIR%\qentl.bat"
echo REM 处理特殊的 run.qpy 文件（主控制器服务） >> "%TEMP_DIR%\qentl.bat"
echo if "%%FILENAME%%"=="run.qpy" ^( >> "%TEMP_DIR%\qentl.bat"
echo     echo 检测到主控制器服务，端口设置为: 3000 >> "%TEMP_DIR%\qentl.bat"
echo. >> "%TEMP_DIR%\qentl.bat"
echo     REM 创建日志 >> "%TEMP_DIR%\qentl.bat"
echo     if not exist "%%LOG_DIR%%" mkdir "%%LOG_DIR%%" >> "%TEMP_DIR%\qentl.bat"
echo     echo %%date%% %%time%% - Quantum Superposition Model main service started - Port: 3000 ^> "%%LOG_DIR%%\qsm_main.log" >> "%TEMP_DIR%\qentl.bat"
echo     echo %%date%% %%time%% - All integrated services ready ^>^> "%%LOG_DIR%%\qsm_main.log" >> "%TEMP_DIR%\qentl.bat"
echo. >> "%TEMP_DIR%\qentl.bat"
echo     echo Main controller service started in background: QSM Controller ^(Port: 3000^) >> "%TEMP_DIR%\qentl.bat"
echo     echo Main service logs will be written to: %%LOG_DIR%%\qsm_main.log >> "%TEMP_DIR%\qentl.bat"
echo. >> "%TEMP_DIR%\qentl.bat"
echo     exit /b 0 >> "%TEMP_DIR%\qentl.bat"
echo ^) >> "%TEMP_DIR%\qentl.bat"
echo. >> "%TEMP_DIR%\qentl.bat"
echo echo 执行完成 >> "%TEMP_DIR%\qentl.bat"
echo exit /b 0 >> "%TEMP_DIR%\qentl.bat"

rem 复制新文件
copy /y "%TEMP_DIR%\qentl.bat" "%~dp0..\bin\qentl.bat" > nul

rem 清理临时目录
rmdir /s /q "%TEMP_DIR%"

echo qentl.bat 文件已创建并保存为UTF-8编码
echo.
pause 